use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// record one file's `token->cnt`
pub type TF = HashMap<String, usize>;
pub type Index = HashMap<PathBuf, Doc>;
/// the token count of occurrence of all files
pub type DF = HashMap<String, usize>;
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Model {
    df: DF,
    index: Index,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct Doc {
    tf: TF,
    ts: std::time::SystemTime,
}
/// 批处理操作
pub type Bulk<T> = Vec<T>;
/// 对Model的单次操作
pub enum Update {
    //df/tf term + cnt 统一在执行后如果为0进行删除
    Modify {
        t: Modified,
        term: String,
        cnt: isize,
    },
    //remove path
    Remove(std::path::PathBuf),
    Set(std::path::PathBuf, std::time::SystemTime),
}
pub enum Modified {
    DF,
    TF(std::path::PathBuf),
}
impl Model {
    pub fn new(df: DF, index: Index) -> Self {
        Self { df, index }
    }
    pub fn index(&self) -> &Index {
        &self.index
    }
    pub fn df(&self) -> &DF {
        &self.df
    }
    pub fn index_mut(&mut self) -> &mut Index {
        &mut self.index
    }
    pub fn df_mut(&mut self) -> &mut DF {
        &mut self.df
    }
    pub fn is_empty(&self) -> bool {
        self.df().is_empty() && self.index().is_empty()
    }
    pub fn apply(&mut self, bulk: Bulk<Update>) {
        bulk.into_iter().for_each(|cmd| cmd.exec(self));
    }
}
impl Update {
    pub fn modify(t: Modified, term: String, cnt: isize) -> Self {
        Self::Modify { t, term, cnt }
    }
    pub fn remove(path: std::path::PathBuf) -> Self {
        Self::Remove(path)
    }
    pub fn set(path: std::path::PathBuf, ts: std::time::SystemTime) -> Self {
        Self::Set(path, ts)
    }
    /// call one Update executed on the model
    pub(self) fn exec(self, model: &mut Model) {
        match self {
            Self::Modify { t, term, cnt } => {
                let map = match t {
                    Modified::DF => model.df_mut(),
                    Modified::TF(path) => model.index_mut().get_mut(&path).unwrap().get_tf_mut(),
                };
                let mut need_to_remove = false;
                map.entry(term.clone())
                    .and_modify(|old_cnt| {
                        *old_cnt = (*old_cnt as isize + cnt) as usize;
                        need_to_remove = if *old_cnt == 0 { true } else { false }
                    })
                    .or_insert(cnt as usize);
                //如果结果为0，删掉
                if need_to_remove {
                    map.remove(&term);
                }
            }
            Self::Remove(path) => {
                model.index_mut().remove(&path);
            }
            Self::Set(path, ts) => {
                model
                    .index_mut()
                    .entry(path)
                    .and_modify(|doc| doc.set_ts(ts));
            }
        }
    }
}
impl Doc {
    pub fn new(tf: TF, ts: std::time::SystemTime) -> Self {
        Self { tf, ts }
    }
    pub fn get_tf(&self) -> &TF {
        &self.tf
    }
    pub fn get_ts(&self) -> std::time::SystemTime {
        self.ts
    }
    pub fn get_tf_mut(&mut self) -> &mut TF {
        &mut self.tf
    }
    pub fn set_ts(&mut self, ts: std::time::SystemTime) {
        self.ts = ts;
    }
    /// calculate the diff set of two doc and convert it into the Bulk
    pub(crate) fn diff(&self, old: &Self, path: std::path::PathBuf) -> Bulk<Update> {
        let mut bulk = Bulk::new();
        //update: set sys_time
        bulk.push(Update::set(path.clone(), self.ts));
        let new = self.get_tf();
        let old = old.get_tf();
        //1 公共的词数量变化
        for (term, cnt) in new {
            if let Some(old_cnt) = old.get(term) {
                //update old[term]+=cnt-old_cnt
                bulk.push(Update::modify(
                    Modified::TF(path.clone()),
                    term.clone(),
                    (*cnt as isize - *old_cnt as isize) as isize,
                ));
            } else {
                //2 新增词的数量变化
                //update: df[term]+=1
                bulk.push(Update::modify(Modified::DF, term.clone(), 1));
                //update:old[term]+=cnt
                bulk.push(Update::modify(
                    Modified::TF(path.clone()),
                    term.clone(),
                    *cnt as isize,
                ));
            }
        }
        //3 删除词的数量变化
        for (remove_term, cnt) in old {
            if new.get(remove_term).is_none() {
                //update: df[remove_term]-=1
                bulk.push(Update::modify(Modified::DF, remove_term.clone(), -1));
                //update: old[remove_term]-=cnt
                bulk.push(Update::modify(
                    Modified::TF(path.clone()),
                    remove_term.clone(),
                    -(*cnt as isize),
                ));
            }
        }
        bulk
    }
}
/// tests generated by GPT-6 Astra
#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::time::{Duration, SystemTime};

    fn tf(entries: &[(&str, usize)]) -> TF {
        entries
            .iter()
            .map(|(term, cnt)| (term.to_string(), *cnt))
            .collect()
    }

    fn model_with_docs(docs: Vec<(PathBuf, Doc)>) -> Model {
        let mut df = DF::new();
        for (_, doc) in &docs {
            for term in doc.get_tf().keys() {
                *df.entry(term.clone()).or_insert(0) += 1;
            }
        }
        Model::new(df, docs.into_iter().collect())
    }

    #[test]
    fn diff_updates_tf_df_and_timestamp() {
        let path = PathBuf::from("changed.xml");
        let ts = SystemTime::UNIX_EPOCH;
        let old = Doc::new(
            tf(&[("rust", 5), ("index", 1), ("gone", 2), ("shared", 3)]),
            ts,
        );
        let other = Doc::new(tf(&[("shared", 1), ("network", 2)]), ts);
        let new = Doc::new(
            tf(&[("rust", 2), ("index", 4), ("fresh", 3), ("network", 1)]),
            ts + Duration::from_secs(1),
        );
        let bulk = new.diff(&old, path.clone());
        let other_path = PathBuf::from("other.xml");
        let mut model = model_with_docs(vec![(path.clone(), old), (other_path.clone(), other)]);
        model.apply(bulk);

        assert_eq!(model.index()[&path].get_tf(), new.get_tf());
        assert_eq!(model.index()[&path].get_ts(), new.get_ts());
        assert_eq!(
            model.df(),
            &tf(&[
                ("rust", 1),
                ("index", 1),
                ("fresh", 1),
                ("network", 2),
                ("shared", 1)
            ])
        );
        assert_eq!(
            model.index()[&other_path].get_tf(),
            &tf(&[("shared", 1), ("network", 2)])
        );
    }

    #[test]
    fn diff_can_clear_all_terms_without_removing_document() {
        let path = PathBuf::from("empty.xml");
        let ts = SystemTime::UNIX_EPOCH;
        let old = Doc::new(tf(&[("rust", 3)]), ts);
        let new = Doc::new(TF::new(), ts + Duration::from_secs(1));
        let bulk = new.diff(&old, path.clone());
        let mut model = model_with_docs(vec![(path.clone(), old)]);
        model.apply(bulk);

        assert!(model.df().is_empty());
        assert!(model.index()[&path].get_tf().is_empty());
        assert_eq!(model.index()[&path].get_ts(), new.get_ts());
    }

    // 每个测试使用独立临时目录；通过旧时间戳触发更新，不依赖 sleep。
    struct Fixture(PathBuf);

    impl Fixture {
        fn new() -> Self {
            static NEXT: AtomicUsize = AtomicUsize::new(0);
            let path = std::env::temp_dir().join(format!(
                "search-core-reindex-{}-{}-{}",
                std::process::id(),
                SystemTime::now()
                    .duration_since(SystemTime::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos(),
                NEXT.fetch_add(1, Ordering::Relaxed),
            ));
            fs::create_dir(&path).unwrap();
            Self(path)
        }

        fn write(&self, name: &str, content: &str) -> (PathBuf, SystemTime) {
            let path = self.0.join(name);
            fs::write(&path, content).unwrap();
            let ts = fs::metadata(&path).unwrap().modified().unwrap();
            (path, ts)
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).unwrap();
        }
    }

    #[test]
    fn reindex_preserves_unchanged_documents_while_updating_and_deleting() {
        let fixture = Fixture::new();
        let (changed, ts) = fixture.write("changed.xml", "<doc>rust rust fresh</doc>");
        let (unchanged, unchanged_ts) = fixture.write("unchanged.xml", "<doc>rust</doc>");
        let deleted = fixture.0.join("deleted.xml");
        let mut model = model_with_docs(vec![
            (
                changed.clone(),
                Doc::new(tf(&[("rust", 4), ("gone", 1)]), ts - Duration::from_secs(1)),
            ),
            (
                unchanged.clone(),
                Doc::new(tf(&[("rust", 1)]), unchanged_ts),
            ),
            (
                deleted.clone(),
                Doc::new(tf(&[("rust", 2), ("lost", 1)]), ts),
            ),
        ]);

        let bulk = crate::re_index(&model).unwrap();
        model.apply(bulk);

        assert_eq!(model.index().len(), 2);
        assert!(!model.index().contains_key(&deleted));
        assert_eq!(
            model.index()[&changed].get_tf(),
            &tf(&[("rust", 2), ("fresh", 1)])
        );
        assert_eq!(model.index()[&changed].get_ts(), ts);
        assert_eq!(model.index()[&unchanged].get_tf(), &tf(&[("rust", 1)]));
        assert_eq!(model.index()[&unchanged].get_ts(), unchanged_ts);
        assert_eq!(model.df(), &tf(&[("rust", 2), ("fresh", 1)]));
        assert!(crate::re_index(&model).unwrap().is_empty());
    }

    #[test]
    fn reindex_handles_deletion_without_modified_documents() {
        let fixture = Fixture::new();
        let (unchanged, ts) = fixture.write("unchanged.xml", "<doc>rust</doc>");
        let deleted = fixture.0.join("deleted.xml");
        let mut model = model_with_docs(vec![
            (unchanged.clone(), Doc::new(tf(&[("rust", 1)]), ts)),
            (deleted, Doc::new(tf(&[("rust", 2), ("lost", 1)]), ts)),
        ]);
        let bulk = crate::re_index(&model).unwrap();
        model.apply(bulk);

        assert_eq!(model.index().len(), 1);
        assert!(model.index().contains_key(&unchanged));
        assert_eq!(model.df(), &tf(&[("rust", 1)]));

        fs::remove_file(&unchanged).unwrap();
        let bulk = crate::re_index(&model).unwrap();
        model.apply(bulk);
        assert!(model.is_empty());
    }

    #[test]
    fn reindex_only_updates_timestamp_when_terms_are_unchanged() {
        let fixture = Fixture::new();
        let (path, ts) = fixture.write("same.xml", "<doc>rust rust</doc>");
        let mut model = model_with_docs(vec![(
            path.clone(),
            Doc::new(tf(&[("rust", 2)]), ts - Duration::from_secs(1)),
        )]);
        let bulk = crate::re_index(&model).unwrap();
        model.apply(bulk);

        assert_eq!(model.index()[&path].get_tf(), &tf(&[("rust", 2)]));
        assert_eq!(model.df(), &tf(&[("rust", 1)]));
        assert_eq!(model.index()[&path].get_ts(), ts);
    }
}
